### ISSUE TITLE
dotenv_config.js?v=f92e931e:399 Uncaught TypeError: Cannot read properties of undefined (reading 'DOTENV_CONFIG_ENCODING') 

### ISSUE THREAD

**Issue by ccfiel** [motdotla/dotenv#844] opened 2024-10-20 09:54 UTC
When I put `import 'dotenv/config'`, this error will occur. Any idea how to resolve this issue?

package version: ` "dotenv": "^16.4.5",`
node version: `v20.9.0`
app: `react`
os: `macOS 15.0.11

![SCR-20241020-pqrf](https://github.com/user-attachments/assets/f4afacce-252e-4a60-b9bb-26c9873cf629)

**Comment by motdotla** [comment] 2024-11-18 18:35
this looks like something unique to your machine @ccfiel. maybe try swapping in [dotenvx](https://github.com/dotenvx/dotenvx) instead? it has better debugging.

**Comment by V0000DY** [comment] 2024-12-03 04:16
Hello, Mot! Same problem: when i put `import 'dotenv/config'` I get the following error: 
![image](https://github.com/user-attachments/assets/84f8f112-a752-4455-8de0-fda9a95c1307)
Can you suggest solutions? 
package version:  "dotenv": "^16.4.5",
node version: v23.3.0
app: vite-react

**Comment by motdotla** [comment] 2024-12-03 17:23
can you please share more about your setup here so I can reproduce? An example repo would be helpful please.

closing until then as I can't reproduce.

**Closed by motdotla** 2024-12-03 17:23 UTC
