### ISSUE TITLE
How to use different environments

### ISSUE THREAD

**Issue by antond1990** [motdotla/dotenv#474] opened 2020-06-02 11:08 UTC
I want to use some npm packages in a symfony app where I use different environments (local dev, staging, live, ...). It seems that your package only reads the `.env` file, but not `.env.local` and other .env files for different environments.

The .env-File is like a template to configurate. I copy it in the environment. .env is managed via git, but not the other .env-Files like `.env.local`

**Comment by ThomasGHenry** [comment] 2020-06-09 19:16
I came here to ask exactly this. The readme says what not to do, but offers no clear guidance (that I saw) on what ought to be done instead.

Perhaps this section can be expanded...?
https://github.com/motdotla/dotenv#should-i-have-multiple-env-files

**Comment by mdoliner-st** [comment] 2020-06-16 17:13
This is possibly a duplicate of https://github.com/motdotla/dotenv/issues/437

**Comment by plashenkov** [comment] 2020-06-22 14:01
It's a very common and practical approach to use `.env`, `.env.local`, etc. Here are the examples:
- https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local (Symfony)
- https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables (Next.js)
- https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used (Create React App)

This statement — https://github.com/motdotla/dotenv#should-i-have-multiple-env-files — is really confusing and looks more like a dogma.

**Comment by mdoliner-st** [comment] 2020-06-23 21:02
I recently learned about https://www.npmjs.com/package/dotenv-flow, which might address some people's needs.

**Comment by j-zimnowoda** [comment] 2020-06-24 12:12
I also noticed that if you have .env in different directories e.g.:
```
.env
A/.env
```
and try to read from A/.env:
```
dotEnv.config({ path: 'A/.env')})
```
Then both .env and A/.env is read. 
Can you confirm that issue ?
```
"dotenv": "^8.2.0",
```

**Comment by jcblw** [comment] 2020-07-20 16:12
I would recommend using dotenv flow! Its a great package and uses this package at its core. Sorry for the dogmatic phrasing in the README, the opinions in the readme have not been updated for a while. There have been lots of discussions about that one part of the readme. Closing this issue for now.

**Closed by jcblw** 2020-07-20 16:12 UTC

**Comment by motdotla** [comment] 2022-03-12 07:01
For anyone visiting this, we now recommend using the dotenv-cli. It allows you to switch between different environments and manage multiple environments. It's pretty great! 

https://github.com/dotenv-org/cli

**Comment by joshuat** [comment] 2022-08-06 04:23
@motdotla I know this issue has had a lot of discussion and I don't mean to resurface it yet again, but would you accept a PR adding multiple environment support? I would imagine it to behave similarly to `foreman` and I imagine it would look something like this:

```
require('dotenv').config({
  path: ['.common.env', '.env'],
});

process.env.DOTENV_CONFIG_PATH=.common.env,.env
```

I know the dotenv ecosystem has grown quite a bit so I completely understand if this is something you'd rather not take on the responsibility of maintaining, I just wanted to touch base before forking or looking for alternatives. Thanks!
